"use client";
import {useEffect,useState} from "react";
import StatusFilter from "@/app/components/status-filter";
import {createClient} from "@/lib/supabase";
type Job={id:string;job_number:string;status:string;service_date:string;customers:{name:string}|null;job_vehicles:{unit_number:string|null;serial_number:string|null;work_performed:string}[]};
export default function FieldDashboard(){
 const [jobs,setJobs]=useState<Job[]>([]),[name,setName]=useState(""),[filter,setFilter]=useState("open"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{async function load(){try{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){window.location.replace("/");return}const {data:profile,error:pe}=await db.from("profiles").select("full_name,active,role").eq("id",user.id).single();if(pe)throw pe;if(!profile.active)throw new Error("Your account is inactive. Contact admin.");if(profile.role==="admin"){window.location.replace("/dashboard");return}setName(profile.full_name);const {data,error}=await db.from("jobs").select("id,job_number,status,service_date,customers(name),job_vehicles(unit_number,serial_number,work_performed)").eq("technician_id",user.id).is("removed_at",null).order("updated_at",{ascending:false});if(error)throw error;setJobs((data||[]) as unknown as Job[])}catch(e){setError((e as Error).message)}finally{setLoading(false)}}load();const refresh=()=>load();window.addEventListener("focus",refresh);return()=>window.removeEventListener("focus",refresh)},[]);
 const open=jobs.filter(j=>j.status!=="closed").length,closed=jobs.length-open;
 const shown=jobs.filter(j=>(filter==="all"||(filter==="closed"?j.status==="closed":j.status!=="closed"))&&[j.job_number,j.customers?.name,j.service_date,...j.job_vehicles.flatMap(v=>[v.unit_number,v.serial_number,v.work_performed])].join(" ").toLowerCase().includes(search.toLowerCase()));
 return <main><header className="field-header"><span className="app-brand"><span className="brand-badge">CG</span><strong>CAM GOLF</strong></span><button className="secondary" onClick={async()=>{await createClient().auth.signOut();window.location.replace("/")}}>Sign out</button></header><h1>Hello{name?", "+name:""}.</h1><p className="muted">Your job cards, in one place.</p>{error&&<p className="notice error" role="alert">{error}</p>}{loading?<p role="status">Loading your jobs…</p>:<><section className="field-cards"><a className="field-card new" href="/field/jobs/new">＋ New Job</a><button className="field-card" aria-pressed={filter==="open"} onClick={()=>setFilter("open")}><strong>{open}</strong>Open Jobs</button><button className="field-card" aria-pressed={filter==="closed"} onClick={()=>setFilter("closed")}><strong>{closed}</strong>Closed Jobs</button></section><div className="field-search"><label>Search jobs<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Customer, car, reference or work"/></label><StatusFilter value={filter} onChange={setFilter}/></div><section className="field-list">{shown.map(j=><a key={j.id} href={"/field/jobs/"+j.id} className="field-job"><span className={"field-status pill "+(j.status==="closed"?"closed":"open")}>{j.status==="closed"?"Closed":"Open"}</span><small>#{j.job_number}</small><strong>{j.customers?.name||"Customer"}</strong><small>{new Date(j.service_date+"T12:00:00").toLocaleDateString("en-ZA",{day:"2-digit",month:"short",year:"numeric"})} · {j.job_vehicles.length} car{j.job_vehicles.length===1?"":"s"}</small><span className="job-open-hint">{j.status==="closed"?"View job":"Open job"} <span aria-hidden="true">→</span></span></a>)}{!shown.length&&<p className="field-empty">No jobs match this view.</p>}</section></>}</main>
}
