"use client";
import {useId,useState} from "react";
export type PartEntry={part_number:string;description:string;quantity:string;unit_cost:string};
export type PartSuggestion={part_number:string|null;description:string;default_cost:number|null};
export default function CartParts({value,onChange,catalog,disabled=false}:{value:PartEntry[];onChange:(parts:PartEntry[])=>void;catalog:PartSuggestion[];disabled?:boolean}){
 const listId=useId(),[search,setSearch]=useState("");
 function add(){if(!search.trim())return;const match=catalog.find(p=>p.description===search||p.part_number===search);onChange([...value,{part_number:match?.part_number||"",description:match?.description||search.trim(),quantity:"1",unit_cost:match?.default_cost==null?"":String(match.default_cost)}]);setSearch("")}
 function update(index:number,patch:Partial<PartEntry>){onChange(value.map((part,i)=>i===index?{...part,...patch}:part))}
 return <fieldset className="cart-parts" disabled={disabled}><legend>Parts used on this cart <span>(optional)</span></legend><div className="part-picker"><label>Find or add a part<input list={listId} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();add()}}} placeholder="Search parts or type a new description"/></label><button type="button" className="secondary" disabled={!search.trim()} onClick={add}>Add part</button></div><datalist id={listId}>{catalog.map((part,i)=><option key={i} value={part.description}>{part.part_number||""}</option>)}</datalist>
 {value.length===0?<p className="empty-inline">No parts added for this cart.</p>:value.map((part,index)=><div className="part-row" key={index}><label>Part number<input value={part.part_number} onChange={e=>update(index,{part_number:e.target.value})}/></label><label>Description<input required list={listId} value={part.description} onChange={e=>{const description=e.target.value,match=catalog.find(p=>p.description===description);update(index,{description,...(match?{part_number:match.part_number||"",unit_cost:match.default_cost==null?"":String(match.default_cost)}:{})})}}/></label><label>Qty<input required type="number" min="0.01" step="0.01" value={part.quantity} onChange={e=>update(index,{quantity:e.target.value})}/></label><label>Unit cost<input type="number" min="0" step="0.01" value={part.unit_cost} onChange={e=>update(index,{unit_cost:e.target.value})}/></label><button type="button" className="text-button" onClick={()=>onChange(value.filter((_,i)=>i!==index))}>Remove</button></div>)}</fieldset>;
}
