"use client";
import {FormEvent,useEffect,useState} from "react";
import {createClient} from "@/lib/supabase";
type Row={id:string;name?:string;address?:string;telephone?:string;email?:string;part_number?:string;description?:string;default_cost?:number|null};
export default function Catalog({kind}:{kind:"customers"|"parts"}){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<Row>({id:""}),[message,setMessage]=useState(""),[ready,setReady]=useState(false),[saving,setSaving]=useState(false),[query,setQuery]=useState("");
 const fields=kind==="customers"?["name","address","telephone","email"]:["part_number","description","default_cost"];
 const labels:Record<string,string>={name:"Customer name",address:"Customer address",telephone:"Telephone",email:"Email",part_number:"Part number",description:"Description",default_cost:"Unit cost"};
 async function load(){const {data,error}=await createClient().from(kind).select("*").order(kind==="customers"?"name":"description");if(error)setMessage(error.message);else setRows(data||[])}
 useEffect(()=>{(async()=>{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){window.location.href="/";return}const {data}=await db.from("profiles").select("role").eq("id",user.id).single();if(data?.role!=="admin"){setMessage("Administrator access required.");return}setReady(true);await load()})()},[kind]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setMessage("");try{const values:Record<string,unknown>={};for(const field of fields){const raw=selected[field as keyof Row];values[field]=field==="default_cost"?(raw==null||raw===""?null:Number(raw)):String(raw??"").trim()||null}const db=createClient();const result=selected.id?await db.from(kind).update(values).eq("id",selected.id).select("id").single():await db.from(kind).insert(values).select("id").single();if(result.error)throw result.error;await load();setSelected({id:""});setMessage("Saved successfully.")}catch(e){setMessage((e as {message?:string}).message||"Unable to save.")}finally{setSaving(false)}}
 return <main className="form-page"><header><a href="/dashboard">← Job cards</a><a href={kind==="customers"?"/parts":"/customers"}>{kind==="customers"?"Parts":"Customers"}</a></header><h1>{kind==="customers"?"Customers":"Parts"}</h1><p className="muted">{kind==="customers"?"Save customer details and their address for future job cards.":"Preload parts here, then select them on a job card. Changing a catalogue price does not change existing job costs."}</p>{message&&<div className="notice" role="status">{message}</div>}{ready&&<><form onSubmit={save} className="form-section"><div className="section-heading"><h2>{selected.id?"Edit":"Add"} {kind==="customers"?"customer":"part"}</h2>{selected.id&&<button type="button" className="secondary" onClick={()=>setSelected({id:""})}>Cancel edit</button>}</div><div className="grid">{fields.map(field=><label key={field}>{labels[field]}<input required={field==="name"||field==="description"} type={field==="default_cost"?"number":field==="email"?"email":"text"} min={field==="default_cost"?0:undefined} step={field==="default_cost"?"0.01":undefined} value={selected[field as keyof Row]??""} onChange={e=>setSelected({...selected,[field]:e.target.value})}/></label>)}</div><button disabled={saving}>{saving?"Saving…":"Save"}</button></form><input aria-label="Search" placeholder="Search…" value={query} onChange={e=>setQuery(e.target.value)}/><section className="form-section">{rows.filter(row=>fields.some(field=>String(row[field as keyof Row]??"").toLowerCase().includes(query.toLowerCase()))).map(row=><article key={row.id} className="vehicle"><div className="section-heading"><div><strong>{row.name||row.description}</strong><p className="muted">{kind==="customers"?row.address:[row.part_number,row.default_cost!=null?"R "+Number(row.default_cost).toFixed(2):""].filter(Boolean).join(" · ")}</p></div><button className="secondary" onClick={()=>{setSelected(row);window.scrollTo({top:0,behavior:"smooth"})}}>Edit</button></div></article>)}{rows.length===0&&<p>No {kind} added yet.</p>}</section></>}</main>
}
