"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import {createClient} from "@/lib/supabase";
import SpeechInput from "./speech-input";
import JobPhotos,{type PhotoHandle} from "./job-photos";
type Car={model:string;amp_hours:string;id:string;unit_number:string;serial_number:string;work_performed:string;attention_notes:string};
const blank=():Car=>({model:"",amp_hours:"",id:crypto.randomUUID(),unit_number:"",serial_number:"",work_performed:"",attention_notes:""});
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")};
export default function FieldEditor({jobId}:{jobId?:string}){
 const [ready,setReady]=useState(false),[closed,setClosed]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(""),[dirty,setDirty]=useState(false);
 const [customers,setCustomers]=useState<{id:string;name:string}[]>([]),[customer,setCustomer]=useState(""),[date,setDate]=useState(today),[km,setKm]=useState(""),[hours,setHours]=useState(""),[notes,setNotes]=useState(""),[cars,setCars]=useState<Car[]>([]),[number,setNumber]=useState("");
 const photos=useRef<PhotoHandle>(null);const [photosBusy,setPhotosBusy]=useState(false); const saved=useRef(false); const requestId=useRef<string>(""),lastCar=useRef<HTMLElement|null>(null);
 useEffect(()=>{requestId.current=jobId||crypto.randomUUID();(async()=>{try{const db=createClient();const {data:{user}}=await db.auth.getUser();if(!user){window.location.replace("/");return}const {data:profile,error:pe}=await db.from("profiles").select("role,active").eq("id",user.id).single();if(pe)throw pe;if(!profile.active)throw new Error("Account inactive. Contact admin.");if(profile.role!=="technician"){window.location.replace(jobId?"/jobs/"+jobId:"/jobs/new");return}const {data:cs,error:ce}=await db.from("customers").select("id,name").is("removed_at",null).order("name");if(ce)throw ce;setCustomers(cs||[]);if(jobId){const {data,error}=await db.from("jobs").select("job_number,status,service_date,travelling_km,duration_hours,general_notes,customers(name),job_vehicles(id,model,amp_hours,unit_number,serial_number,work_performed,attention_notes,sort_order)").eq("id",jobId).is("removed_at",null).eq("technician_id",user.id).single();if(error)throw new Error("This job is unavailable or is not assigned to you.");const row=data as any;setNumber(row.job_number);setClosed(row.status==="closed");setCustomer(row.customers?.name||"");setDate(row.service_date);setKm(row.travelling_km?.toString()||"");setHours(row.duration_hours?.toString()||"");setNotes(row.general_notes||"");setCars(row.job_vehicles.sort((a:any,b:any)=>a.sort_order-b.sort_order).map((c:any)=>({...c,model:c.model||"",amp_hours:c.amp_hours?.toString()||"",unit_number:c.unit_number||"",serial_number:c.serial_number||"",attention_notes:c.attention_notes||""})))}else setCars([blank()]);setReady(true)}catch(e){setError((e as Error).message)}})()},[jobId]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty&&!saved.current){e.preventDefault();e.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 function carChange(id:string,key:keyof Car,value:string){setDirty(true);setCars(all=>all.map(c=>c.id===id?{...c,[key]:value}:c))}
 async function save(e:FormEvent){e.preventDefault();if(saving||photosBusy||closed)return;setError("");if(!customer.trim()||!date||!cars.length||cars.some(c=>!c.unit_number.trim()||!c.work_performed.trim())){setError("Add a customer, date, and at least one car with a unit number and work performed.");return}if(!navigator.onLine){setError("No internet connection. Keep this page open and save when connected.");return}setSaving(true);try{const {error}=await createClient().rpc("save_field_job",{payload:{id:requestId.current,customer_name:customer.trim(),service_date:date,travelling_km:km||null,duration_hours:hours||null,general_notes:notes,cars}});if(error)throw error;await photos.current?.upload(requestId.current);saved.current=true;setDirty(false);window.location.assign("/field")}catch(e){setError((e as {message?:string}).message||"Could not save. Your entries are still here; please retry.");setSaving(false)}}
 return <main><header className="field-header"><a href="/field" onClick={e=>{if(dirty&&!confirm("Leave without saving your changes?"))e.preventDefault()}}>← My job cards</a><strong>CAM GOLF</strong></header><h1>{jobId?"Job #"+number:"New job"}</h1>{closed?<p className="notice">Closed job — view only. Contact admin for changes.</p>:<p className="muted">* Required. Save while connected to the internet.</p>}{error&&<p className="notice error" role="alert">{error}</p>}{!ready?(!error&&<p>Loading…</p>):<form className={"field-form "+(closed?"field-readonly":"")} onSubmit={save} onChange={()=>setDirty(true)}><fieldset className="field-section" disabled={closed||saving}><label>Customer *<input list="field-customers" required value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Select or type a customer"/><datalist id="field-customers">{customers.map(c=><option key={c.id} value={c.name}/>)}</datalist></label><label>Date *<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><div className="field-pair"><label>KMs travelled<input type="number" min="0" step="0.1" inputMode="decimal" value={km} onChange={e=>setKm(e.target.value)}/></label><label>Duration in hours<input type="number" min="0" step="0.25" inputMode="decimal" value={hours} onChange={e=>setHours(e.target.value)}/></label></div></fieldset>
 {cars.map((car,index)=><fieldset key={car.id} className="field-section" disabled={closed||saving} ref={node=>{if(index===cars.length-1)lastCar.current=node}}><div className="field-car-title"><h2>Car {index+1} of {cars.length}</h2>{!closed&&cars.length>1&&<button type="button" className="secondary" onClick={()=>{if(confirm("Remove this car from the job?")){setCars(all=>all.filter(c=>c.id!==car.id));setDirty(true)}}}>Remove</button>}</div><label>Model<input value={car.model} onChange={e=>carChange(car.id,"model",e.target.value)}/></label><label>AMP hours<input type="number" min="0" step="0.01" inputMode="decimal" value={car.amp_hours} onChange={e=>carChange(car.id,"amp_hours",e.target.value)}/></label><label>Cart number *<input required value={car.unit_number} onChange={e=>carChange(car.id,"unit_number",e.target.value)}/></label><label>Serial number<input value={car.serial_number} onChange={e=>carChange(car.id,"serial_number",e.target.value)}/></label><SpeechInput label="Work performed" required value={car.work_performed} disabled={closed||saving} onChange={v=>carChange(car.id,"work_performed",v)}/><SpeechInput label="Items requiring attention" value={car.attention_notes} disabled={closed||saving} onChange={v=>carChange(car.id,"attention_notes",v)}/></fieldset>)}
 {!closed&&<button type="button" className="secondary" disabled={saving} onClick={()=>{setCars(all=>[...all,blank()]);setDirty(true);setTimeout(()=>{lastCar.current?.scrollIntoView({behavior:"smooth",block:"start"});lastCar.current?.querySelector("input")?.focus({preventScroll:true})},60)}}>＋ Add another car ({cars.length} added)</button>}
 <JobPhotos ref={photos} jobId={jobId} readOnly={closed} disabled={saving} onDirty={()=>setDirty(true)} onBusy={setPhotosBusy}/><fieldset className="field-section" disabled={closed||saving}><SpeechInput label="Additional notes" value={notes} disabled={closed||saving} onChange={v=>{setNotes(v);setDirty(true)}}/>{!closed&&<small className="speech-note">Voice typing is controlled by your phone’s keyboard. Check the text before saving.</small>}</fieldset>{error&&<p className="notice error" role="alert">{error}</p>}{!closed&&<button className="field-save" disabled={saving||photosBusy}>{saving?"Saving job…":"SAVE JOB"}</button>}</form>}</main>
}
