"use client";

import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase";

type Vehicle = { unit_number:string|null; serial_number:string|null; work_performed:string; attention_notes:string|null; sort_order:number };
type Job = { id:string; report_number:number; service_date:string; travelling_km:number|null; duration_hours:number|null; general_notes:string|null; customers:{name:string}|null; sites:{name:string}|null; profiles:{full_name:string}|null; job_vehicles:Vehicle[] };

const checks=["Service","Brakes","Oil","Water","Hardware","Wheels & Tyres (check)","Ignition","General Appearance of Car","Charger"];

export default function ReportPage(){
 const {id}=useParams<{id:string}>(); const router=useRouter(); const [job,setJob]=useState<Job|null>(null); const [error,setError]=useState(""); const [downloading,setDownloading]=useState(false);
 useEffect(()=>{(async()=>{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/");return}const {data,error}=await supabase.from("jobs").select("id,report_number,service_date,travelling_km,duration_hours,general_notes,customers(name),sites(name),profiles!jobs_technician_id_fkey(full_name),job_vehicles(unit_number,serial_number,work_performed,attention_notes,sort_order)").eq("id",id).single();if(error)setError(error.message);else{const value=data as unknown as Job;value.job_vehicles.sort((a,b)=>a.sort_order-b.sort_order);setJob(value)}})()},[id,router]);
 async function download(){if(!job)return;setDownloading(true);try{const response=await fetch(`/api/jobs/${id}/report`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportNumber:job.report_number,customerName:job.customers?.name,siteName:job.sites?.name,serviceDate:job.service_date,travellingKm:job.travelling_km,durationHours:job.duration_hours,technicianName:job.profiles?.full_name,generalNotes:job.general_notes,vehicles:job.job_vehicles.map(v=>({unitNumber:v.unit_number,serialNumber:v.serial_number,workPerformed:v.work_performed,attentionNotes:v.attention_notes}))})});if(!response.ok)throw new Error("The PDF could not be created.");const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`EZGO-${String(job.report_number).padStart(5,"0")}.pdf`;a.click();URL.revokeObjectURL(url)}catch(e){setError(e instanceof Error?e.message:"The PDF could not be created.")}finally{setDownloading(false)}}
 function email(){if(!job)return;const subject=`EZGO Service Report ${String(job.report_number).padStart(5,"0")} – ${job.customers?.name||"Customer"}`;const body=`Please find the CAM Golf service report for ${job.customers?.name||"the customer"}, ${job.sites?.name||"site"}.\n\nReport number: ${String(job.report_number).padStart(5,"0")}\nService date: ${job.service_date}\n\nPlease download the PDF first and attach it to this email.`;window.location.href=`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
 if(error&&!job)return <main className="report-shell"><div className="notice error">{error}</div><a href="/dashboard">← Back to job cards</a></main>;
 if(!job)return <main className="report-shell"><div className="notice">Loading report…</div></main>;
 const rows=Array.from({length:Math.max(10,job.job_vehicles.length)},(_,i)=>job.job_vehicles[i]);
 return <main className="report-shell"><div className="report-toolbar"><div><a href="/dashboard">← Job cards</a><h1>EZGO report preview</h1><p className="muted">This is the client-facing report. Edit the job card to change its contents.</p></div><div className="report-actions"><a className="secondary button-link" href={`/jobs/${id}`}>Edit job</a><button className="secondary" onClick={()=>window.print()}>Print</button><button className="secondary" onClick={email}>Email</button><button onClick={download} disabled={downloading}>{downloading?"Creating…":"Download PDF"}</button></div></div>
 <article className="report-paper"><div className="report-brand"><div><div className="ezgo-wordmark">EZGO</div><strong>A Textron Company</strong></div><div><strong>Boundless Trade 154 (PTY) Ltd</strong><br/><small>Reg No: 2000/025986/07 · Vat Reg No: 4540192863<br/>30 Pioneer Road, Pacaltsdorp Industria<br/>George, 6530<br/>Tel: (044) 878 0282 · info@george.ezgo.co.za</small></div></div>
 <div className="report-title"><h1>SERVICE / INSPECTION CLIENT REPORT</h1><div>Nr: <span className="report-number">{String(job.report_number).padStart(5,"0")}</span></div></div>
 <section className="report-summary"><div><div className="report-field"><strong>To:</strong><span>{job.customers?.name}<br/>{job.sites?.name}</span></div><div className="report-field"><strong>Telephone Nr:</strong><span/></div></div><div><div className="report-field"><strong>Date:</strong><span>{new Date(job.service_date).toLocaleDateString("en-ZA")}</span></div><div className="report-field"><strong>Travelling Km:</strong><span>{job.travelling_km??""}</span></div><div className="report-field"><strong>Duration / Hours:</strong><span>{job.duration_hours??""}</span></div><div className="report-field"><strong>Technician:</strong><span>{job.profiles?.full_name}</span></div></div></section>
 <section className="report-table-wrap"><table className="report-table"><thead><tr><th>Serial Number</th><th>Work performed on the following units</th></tr></thead><tbody>{rows.map((v,i)=><tr key={i}><td>{v?.serial_number||v?.unit_number||""}</td><td>{v?.work_performed||""}</td></tr>)}</tbody></table><table className="report-table"><thead><tr><th>Serial Number</th><th>Items requiring attention</th></tr></thead><tbody>{rows.map((v,i)=><tr key={i}><td>{v?.attention_notes?(v.serial_number||v.unit_number||""):""}</td><td>{v?.attention_notes||""}</td></tr>)}</tbody></table></section>
 <div className="report-notes"><strong>Additional Comments / Notes:</strong><p>{job.general_notes}</p></div><section className="report-footer"><div><strong>Work performed (kindly tick below)</strong><div className="checklist">{checks.map(item=><span key={item}>□ {item}</span>)}</div></div><div><div className="signature-box">CLIENT SIGNATURE:</div><div className="signature-box">CLIENT NAME (Please Print)</div><div className="signature-box">TECHNICIAN SIGNATURE:</div></div></section></article></main>
}
