"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { createClient } from "@/lib/supabase";

type Vehicle={id:string;unit_number:string|null;serial_number:string|null;work_performed:string;attention_notes:string|null};
type Job={id:string;report_number:number;status:string;service_date:string;travelling_km:number|null;duration_hours:number|null;general_notes:string|null;client_name:string|null;customers:{name:string;telephone:string|null}|null;sites:{name:string;address:string|null}|null;profiles:{full_name:string}|null;job_vehicles:Vehicle[]};

export default function JobReview(){
 const {id}=useParams<{id:string}>(); const [job,setJob]=useState<Job|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false);
 useEffect(()=>{const load=async()=>{const {data,error}=await createClient().from("jobs").select("id,report_number,status,service_date,travelling_km,duration_hours,general_notes,client_name,customers(name,telephone),sites(name,address),profiles!jobs_technician_id_fkey(full_name),job_vehicles(id,unit_number,serial_number,work_performed,attention_notes)").eq("id",id).order("sort_order",{referencedTable:"job_vehicles"}).single();if(error)setError(error.message);else setJob(data as unknown as Job)};load()},[id]);
 async function update(values:Partial<Job>){if(!job)return;setSaving(true);const {error}=await createClient().from("jobs").update(values).eq("id",job.id);if(error)setError(error.message);else setJob({...job,...values});setSaving(false)}
 async function download(){if(!job)return;const response=await fetch(`/api/jobs/${job.id}/report`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reportNumber:job.report_number,customerName:job.customers?.name,siteName:job.sites?.name,telephone:job.customers?.telephone,serviceDate:job.service_date,travellingKm:job.travelling_km,durationHours:job.duration_hours,technicianName:job.profiles?.full_name,generalNotes:job.general_notes,vehicles:job.job_vehicles.map(v=>({unitNumber:v.unit_number,serialNumber:v.serial_number,workPerformed:v.work_performed,attentionNotes:v.attention_notes}))})});if(!response.ok){setError("The PDF could not be generated.");return}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`EZGO-${job.report_number}.pdf`;a.click();URL.revokeObjectURL(url)}
 if(error&&!job)return <main className="form-page"><a href="/dashboard">← Job cards</a><div className="notice error">{error}</div></main>;
 if(!job)return <main className="form-page"><div className="notice">Loading job card…</div></main>;
 return <main className="form-page"><header><a href="/dashboard">← Job cards</a><span className="sync">{saving?"Saving…":"Live record"}</span></header><div className="form-title"><div><p className="eyebrow">ADMIN REVIEW</p><h1>{job.customers?.name}</h1><p className="muted">{job.sites?.name} · {job.profiles?.full_name}</p></div><button onClick={download} disabled={job.status!=="closed"}>Download EZGO PDF</button></div>{job.status!=="closed"&&<div className="notice">Close this job before downloading its final client report.</div>}<section className="form-section"><h2>Report details</h2><div className="grid"><label>Report number<input type="number" value={job.report_number} onChange={e=>setJob({...job,report_number:Number(e.target.value)})} onBlur={()=>update({report_number:job.report_number})}/></label><label>Status<select value={job.status} onChange={e=>update({status:e.target.value})}><option value="completed">Completed</option><option value="under_review">Under review</option><option value="returned">Returned for changes</option><option value="closed">Closed</option></select></label><label>Service date<input value={job.service_date} readOnly/></label><label>Technician<input value={job.profiles?.full_name||""} readOnly/></label><label>Travelling kilometres<input value={job.travelling_km??""} readOnly/></label><label>Duration (hours)<input value={job.duration_hours??""} readOnly/></label></div></section><section className="form-section"><h2>Golf cars</h2>{job.job_vehicles.map((v,i)=><article className="vehicle" key={v.id}><h3>Car {i+1}: {v.unit_number||"No unit number"}</h3><p><strong>Serial:</strong> {v.serial_number||"Not supplied"}</p><p><strong>Work performed:</strong><br/>{v.work_performed}</p>{v.attention_notes&&<p><strong>Requires attention:</strong><br/>{v.attention_notes}</p>}</article>)}</section>{job.general_notes&&<section className="form-section"><h2>Additional notes</h2><p>{job.general_notes}</p></section>}</main>
}
